# CMake generated Testfile for 
# Source directory: E:/Graphics/Graphics/Tools/glm/test/perf
# Build directory: E:/Graphics/Graphics/Tools/glm_compile/test/perf
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_div "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Debug/test-perf_matrix_div.exe")
  set_tests_properties(test-perf_matrix_div PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;1;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_div "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Release/test-perf_matrix_div.exe")
  set_tests_properties(test-perf_matrix_div PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;1;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_div "E:/Graphics/Graphics/Tools/glm_compile/test/perf/MinSizeRel/test-perf_matrix_div.exe")
  set_tests_properties(test-perf_matrix_div PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;1;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_div "E:/Graphics/Graphics/Tools/glm_compile/test/perf/RelWithDebInfo/test-perf_matrix_div.exe")
  set_tests_properties(test-perf_matrix_div PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;1;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_div NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_inverse "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Debug/test-perf_matrix_inverse.exe")
  set_tests_properties(test-perf_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;2;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_inverse "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Release/test-perf_matrix_inverse.exe")
  set_tests_properties(test-perf_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;2;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_inverse "E:/Graphics/Graphics/Tools/glm_compile/test/perf/MinSizeRel/test-perf_matrix_inverse.exe")
  set_tests_properties(test-perf_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;2;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_inverse "E:/Graphics/Graphics/Tools/glm_compile/test/perf/RelWithDebInfo/test-perf_matrix_inverse.exe")
  set_tests_properties(test-perf_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;2;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_inverse NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_mul "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Debug/test-perf_matrix_mul.exe")
  set_tests_properties(test-perf_matrix_mul PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;3;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_mul "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Release/test-perf_matrix_mul.exe")
  set_tests_properties(test-perf_matrix_mul PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;3;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_mul "E:/Graphics/Graphics/Tools/glm_compile/test/perf/MinSizeRel/test-perf_matrix_mul.exe")
  set_tests_properties(test-perf_matrix_mul PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;3;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_mul "E:/Graphics/Graphics/Tools/glm_compile/test/perf/RelWithDebInfo/test-perf_matrix_mul.exe")
  set_tests_properties(test-perf_matrix_mul PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;3;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_mul NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_mul_vector "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Debug/test-perf_matrix_mul_vector.exe")
  set_tests_properties(test-perf_matrix_mul_vector PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;4;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_mul_vector "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Release/test-perf_matrix_mul_vector.exe")
  set_tests_properties(test-perf_matrix_mul_vector PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;4;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_mul_vector "E:/Graphics/Graphics/Tools/glm_compile/test/perf/MinSizeRel/test-perf_matrix_mul_vector.exe")
  set_tests_properties(test-perf_matrix_mul_vector PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;4;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_mul_vector "E:/Graphics/Graphics/Tools/glm_compile/test/perf/RelWithDebInfo/test-perf_matrix_mul_vector.exe")
  set_tests_properties(test-perf_matrix_mul_vector PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;4;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_mul_vector NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_matrix_transpose "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Debug/test-perf_matrix_transpose.exe")
  set_tests_properties(test-perf_matrix_transpose PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;5;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_matrix_transpose "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Release/test-perf_matrix_transpose.exe")
  set_tests_properties(test-perf_matrix_transpose PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;5;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_matrix_transpose "E:/Graphics/Graphics/Tools/glm_compile/test/perf/MinSizeRel/test-perf_matrix_transpose.exe")
  set_tests_properties(test-perf_matrix_transpose PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;5;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_matrix_transpose "E:/Graphics/Graphics/Tools/glm_compile/test/perf/RelWithDebInfo/test-perf_matrix_transpose.exe")
  set_tests_properties(test-perf_matrix_transpose PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;5;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_matrix_transpose NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-perf_vector_mul_matrix "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Debug/test-perf_vector_mul_matrix.exe")
  set_tests_properties(test-perf_vector_mul_matrix PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;6;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-perf_vector_mul_matrix "E:/Graphics/Graphics/Tools/glm_compile/test/perf/Release/test-perf_vector_mul_matrix.exe")
  set_tests_properties(test-perf_vector_mul_matrix PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;6;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-perf_vector_mul_matrix "E:/Graphics/Graphics/Tools/glm_compile/test/perf/MinSizeRel/test-perf_vector_mul_matrix.exe")
  set_tests_properties(test-perf_vector_mul_matrix PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;6;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-perf_vector_mul_matrix "E:/Graphics/Graphics/Tools/glm_compile/test/perf/RelWithDebInfo/test-perf_vector_mul_matrix.exe")
  set_tests_properties(test-perf_vector_mul_matrix PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;6;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/perf/CMakeLists.txt;0;")
else()
  add_test(test-perf_vector_mul_matrix NOT_AVAILABLE)
endif()
