# CMake generated Testfile for 
# Source directory: E:/Graphics/Graphics/Tools/glm/test/gtc
# Build directory: E:/Graphics/Graphics/Tools/glm_compile/test/gtc
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_bitfield "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_bitfield.exe")
  set_tests_properties(test-gtc_bitfield PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;1;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_bitfield "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_bitfield.exe")
  set_tests_properties(test-gtc_bitfield PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;1;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_bitfield "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_bitfield.exe")
  set_tests_properties(test-gtc_bitfield PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;1;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_bitfield "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_bitfield.exe")
  set_tests_properties(test-gtc_bitfield PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;1;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_bitfield NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_color_space "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_color_space.exe")
  set_tests_properties(test-gtc_color_space PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;2;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_color_space "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_color_space.exe")
  set_tests_properties(test-gtc_color_space PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;2;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_color_space "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_color_space.exe")
  set_tests_properties(test-gtc_color_space PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;2;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_color_space "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_color_space.exe")
  set_tests_properties(test-gtc_color_space PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;2;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_color_space NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_constants "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_constants.exe")
  set_tests_properties(test-gtc_constants PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;3;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_constants "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_constants.exe")
  set_tests_properties(test-gtc_constants PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;3;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_constants "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_constants.exe")
  set_tests_properties(test-gtc_constants PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;3;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_constants "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_constants.exe")
  set_tests_properties(test-gtc_constants PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;3;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_constants NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_epsilon "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_epsilon.exe")
  set_tests_properties(test-gtc_epsilon PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;4;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_epsilon "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_epsilon.exe")
  set_tests_properties(test-gtc_epsilon PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;4;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_epsilon "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_epsilon.exe")
  set_tests_properties(test-gtc_epsilon PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;4;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_epsilon "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_epsilon.exe")
  set_tests_properties(test-gtc_epsilon PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;4;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_epsilon NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_integer "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_integer.exe")
  set_tests_properties(test-gtc_integer PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;5;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_integer "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_integer.exe")
  set_tests_properties(test-gtc_integer PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;5;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_integer "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_integer.exe")
  set_tests_properties(test-gtc_integer PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;5;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_integer "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_integer.exe")
  set_tests_properties(test-gtc_integer PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;5;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_integer NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_access "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_matrix_access.exe")
  set_tests_properties(test-gtc_matrix_access PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;6;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_access "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_matrix_access.exe")
  set_tests_properties(test-gtc_matrix_access PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;6;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_access "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_matrix_access.exe")
  set_tests_properties(test-gtc_matrix_access PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;6;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_access "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_matrix_access.exe")
  set_tests_properties(test-gtc_matrix_access PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;6;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_matrix_access NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_integer "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_matrix_integer.exe")
  set_tests_properties(test-gtc_matrix_integer PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;7;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_integer "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_matrix_integer.exe")
  set_tests_properties(test-gtc_matrix_integer PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;7;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_integer "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_matrix_integer.exe")
  set_tests_properties(test-gtc_matrix_integer PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;7;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_integer "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_matrix_integer.exe")
  set_tests_properties(test-gtc_matrix_integer PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;7;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_matrix_integer NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_inverse "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_matrix_inverse.exe")
  set_tests_properties(test-gtc_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;8;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_inverse "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_matrix_inverse.exe")
  set_tests_properties(test-gtc_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;8;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_inverse "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_matrix_inverse.exe")
  set_tests_properties(test-gtc_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;8;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_inverse "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_matrix_inverse.exe")
  set_tests_properties(test-gtc_matrix_inverse PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;8;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_matrix_inverse NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_matrix_transform "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_matrix_transform.exe")
  set_tests_properties(test-gtc_matrix_transform PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;9;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_matrix_transform "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_matrix_transform.exe")
  set_tests_properties(test-gtc_matrix_transform PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;9;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_matrix_transform "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_matrix_transform.exe")
  set_tests_properties(test-gtc_matrix_transform PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;9;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_matrix_transform "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_matrix_transform.exe")
  set_tests_properties(test-gtc_matrix_transform PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;9;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_matrix_transform NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_noise "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_noise.exe")
  set_tests_properties(test-gtc_noise PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;10;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_noise "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_noise.exe")
  set_tests_properties(test-gtc_noise PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;10;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_noise "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_noise.exe")
  set_tests_properties(test-gtc_noise PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;10;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_noise "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_noise.exe")
  set_tests_properties(test-gtc_noise PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;10;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_noise NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_packing "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_packing.exe")
  set_tests_properties(test-gtc_packing PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;11;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_packing "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_packing.exe")
  set_tests_properties(test-gtc_packing PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;11;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_packing "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_packing.exe")
  set_tests_properties(test-gtc_packing PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;11;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_packing "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_packing.exe")
  set_tests_properties(test-gtc_packing PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;11;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_packing NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_quaternion "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_quaternion.exe")
  set_tests_properties(test-gtc_quaternion PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;12;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_quaternion "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_quaternion.exe")
  set_tests_properties(test-gtc_quaternion PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;12;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_quaternion "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_quaternion.exe")
  set_tests_properties(test-gtc_quaternion PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;12;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_quaternion "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_quaternion.exe")
  set_tests_properties(test-gtc_quaternion PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;12;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_quaternion NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_random "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_random.exe")
  set_tests_properties(test-gtc_random PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;13;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_random "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_random.exe")
  set_tests_properties(test-gtc_random PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;13;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_random "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_random.exe")
  set_tests_properties(test-gtc_random PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;13;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_random "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_random.exe")
  set_tests_properties(test-gtc_random PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;13;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_random NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_round "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_round.exe")
  set_tests_properties(test-gtc_round PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;14;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_round "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_round.exe")
  set_tests_properties(test-gtc_round PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;14;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_round "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_round.exe")
  set_tests_properties(test-gtc_round PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;14;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_round "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_round.exe")
  set_tests_properties(test-gtc_round PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;14;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_round NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_reciprocal "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_reciprocal.exe")
  set_tests_properties(test-gtc_reciprocal PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;15;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_reciprocal "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_reciprocal.exe")
  set_tests_properties(test-gtc_reciprocal PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;15;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_reciprocal "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_reciprocal.exe")
  set_tests_properties(test-gtc_reciprocal PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;15;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_reciprocal "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_reciprocal.exe")
  set_tests_properties(test-gtc_reciprocal PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;15;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_reciprocal NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_type_aligned "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_type_aligned.exe")
  set_tests_properties(test-gtc_type_aligned PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;16;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_type_aligned "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_type_aligned.exe")
  set_tests_properties(test-gtc_type_aligned PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;16;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_type_aligned "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_type_aligned.exe")
  set_tests_properties(test-gtc_type_aligned PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;16;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_type_aligned "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_type_aligned.exe")
  set_tests_properties(test-gtc_type_aligned PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;16;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_type_aligned NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_type_precision "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_type_precision.exe")
  set_tests_properties(test-gtc_type_precision PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;17;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_type_precision "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_type_precision.exe")
  set_tests_properties(test-gtc_type_precision PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;17;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_type_precision "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_type_precision.exe")
  set_tests_properties(test-gtc_type_precision PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;17;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_type_precision "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_type_precision.exe")
  set_tests_properties(test-gtc_type_precision PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;17;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_type_precision NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_type_ptr "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_type_ptr.exe")
  set_tests_properties(test-gtc_type_ptr PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;18;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_type_ptr "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_type_ptr.exe")
  set_tests_properties(test-gtc_type_ptr PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;18;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_type_ptr "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_type_ptr.exe")
  set_tests_properties(test-gtc_type_ptr PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;18;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_type_ptr "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_type_ptr.exe")
  set_tests_properties(test-gtc_type_ptr PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;18;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_type_ptr NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_ulp "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_ulp.exe")
  set_tests_properties(test-gtc_ulp PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;19;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_ulp "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_ulp.exe")
  set_tests_properties(test-gtc_ulp PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;19;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_ulp "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_ulp.exe")
  set_tests_properties(test-gtc_ulp PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;19;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_ulp "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_ulp.exe")
  set_tests_properties(test-gtc_ulp PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;19;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_ulp NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(test-gtc_vec1 "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Debug/test-gtc_vec1.exe")
  set_tests_properties(test-gtc_vec1 PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;20;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(test-gtc_vec1 "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/Release/test-gtc_vec1.exe")
  set_tests_properties(test-gtc_vec1 PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;20;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(test-gtc_vec1 "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/MinSizeRel/test-gtc_vec1.exe")
  set_tests_properties(test-gtc_vec1 PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;20;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(test-gtc_vec1 "E:/Graphics/Graphics/Tools/glm_compile/test/gtc/RelWithDebInfo/test-gtc_vec1.exe")
  set_tests_properties(test-gtc_vec1 PROPERTIES  _BACKTRACE_TRIPLES "E:/Graphics/Graphics/Tools/glm/test/CMakeLists.txt;231;add_test;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;20;glmCreateTestGTC;E:/Graphics/Graphics/Tools/glm/test/gtc/CMakeLists.txt;0;")
else()
  add_test(test-gtc_vec1 NOT_AVAILABLE)
endif()
